using Microsoft.EntityFrameworkCore;
using RentalTracker.Web.Models;

namespace RentalTracker.Web.Utilities
{
    public static class ModelBuilderExtensions
    {
        public static void Seed(this ModelBuilder modelBuilder)
        {
            //MailLibraries
            modelBuilder.Entity<MailLibrary>()
                .HasData(
                    new MailLibrary
                    {
                        Id = 1,
                        MailUserId = "DNR",
                        EmailAddress = "kpljain21@gmail.com",
                        EmailName = "Rental Tracker",
                        Password = ".",
                        Host = "smtp.gmail.com",
                        Port = 587,
                        EnableSsl = true,
                        UseDefaultCredentials = false,
                        System = true
                    }
            );

            //Country
            modelBuilder.Entity<Country>()
                .HasData(
                    new Country { CountryId = 1, CountryCode = "91", CountryName = "India", ShortName = "IN", CreatedBy = "SystemGenerated" }
            );

            //State
            modelBuilder.Entity<State>()
                .HasData(
                    new State { StateId = 1, CountryId = 1, StateCode = "1", StateName = "Andaman and Nicobar Islands", ShortName = "AD", CreatedBy = "SystemGenerated" },
                    new State { StateId = 2, CountryId = 1, StateCode = "2", StateName = "Andhra Pradesh", ShortName = "AN", CreatedBy = "SystemGenerated" },
                    new State { StateId = 3, CountryId = 1, StateCode = "3", StateName = "Arunachal Pradesh", ShortName = "AP", CreatedBy = "SystemGenerated" },
                    new State { StateId = 4, CountryId = 1, StateCode = "4", StateName = "Assam", ShortName = "AS", CreatedBy = "SystemGenerated" },
                    new State { StateId = 5, CountryId = 1, StateCode = "5", StateName = "Bihar", ShortName = "BH", CreatedBy = "SystemGenerated" },
                    new State { StateId = 6, CountryId = 1, StateCode = "6", StateName = "Chandigarh", ShortName = "CH", CreatedBy = "SystemGenerated" },
                    new State { StateId = 7, CountryId = 1, StateCode = "7", StateName = "Chhattisgarh", ShortName = "CG", CreatedBy = "SystemGenerated" },
                    new State { StateId = 8, CountryId = 1, StateCode = "8", StateName = "Delhi", ShortName = "DL", CreatedBy = "SystemGenerated" },
                    new State { StateId = 9, CountryId = 1, StateCode = "9", StateName = "Goa", ShortName = "GA", CreatedBy = "SystemGenerated" },
                    new State { StateId = 10, CountryId = 1, StateCode = "10", StateName = "Gujarat", ShortName = "GJ", CreatedBy = "SystemGenerated" },
                    new State { StateId = 11, CountryId = 1, StateCode = "11", StateName = "Haryana", ShortName = "HR", CreatedBy = "SystemGenerated" },
                    new State { StateId = 12, CountryId = 1, StateCode = "12", StateName = "Himachal Pradesh", ShortName = "HP", CreatedBy = "SystemGenerated" },
                    new State { StateId = 13, CountryId = 1, StateCode = "13", StateName = "Jammu and Kashmir", ShortName = "JK", CreatedBy = "SystemGenerated" },
                    new State { StateId = 14, CountryId = 1, StateCode = "14", StateName = "Jharkhand", ShortName = "JH", CreatedBy = "SystemGenerated" },
                    new State { StateId = 15, CountryId = 1, StateCode = "15", StateName = "Karnataka", ShortName = "KR", CreatedBy = "SystemGenerated" },
                    new State { StateId = 16, CountryId = 1, StateCode = "16", StateName = "Kerala", ShortName = "KL", CreatedBy = "SystemGenerated" },
                    new State { StateId = 17, CountryId = 1, StateCode = "17", StateName = "Lakshadweep", ShortName = "LW", CreatedBy = "SystemGenerated" },
                    new State { StateId = 18, CountryId = 1, StateCode = "18", StateName = "Madhya Pradesh", ShortName = "MP", CreatedBy = "SystemGenerated" },
                    new State { StateId = 19, CountryId = 1, StateCode = "19", StateName = "Maharashtra", ShortName = "MH", CreatedBy = "SystemGenerated" },
                    new State { StateId = 20, CountryId = 1, StateCode = "20", StateName = "Manipur", ShortName = "MN", CreatedBy = "SystemGenerated" },
                    new State { StateId = 21, CountryId = 1, StateCode = "21", StateName = "Meghalaya", ShortName = "MG", CreatedBy = "SystemGenerated" },
                    new State { StateId = 22, CountryId = 1, StateCode = "22", StateName = "Mizoram", ShortName = "MZ", CreatedBy = "SystemGenerated" },
                    new State { StateId = 23, CountryId = 1, StateCode = "23", StateName = "Nagaland", ShortName = "NG", CreatedBy = "SystemGenerated" },
                    new State { StateId = 24, CountryId = 1, StateCode = "24", StateName = "Odisha", ShortName = "OD", CreatedBy = "SystemGenerated" },
                    new State { StateId = 25, CountryId = 1, StateCode = "25", StateName = "Puducherry", ShortName = "PD", CreatedBy = "SystemGenerated" },
                    new State { StateId = 26, CountryId = 1, StateCode = "26", StateName = "Punjab", ShortName = "PB", CreatedBy = "SystemGenerated" },
                    new State { StateId = 27, CountryId = 1, StateCode = "27", StateName = "Rajasthan", ShortName = "RJ", CreatedBy = "SystemGenerated" },
                    new State { StateId = 28, CountryId = 1, StateCode = "28", StateName = "Sikkim", ShortName = "SK", CreatedBy = "SystemGenerated" },
                    new State { StateId = 29, CountryId = 1, StateCode = "29", StateName = "Tamil Nadu", ShortName = "TN", CreatedBy = "SystemGenerated" },
                    new State { StateId = 30, CountryId = 1, StateCode = "30", StateName = "Telangana", ShortName = "TL", CreatedBy = "SystemGenerated" },
                    new State { StateId = 31, CountryId = 1, StateCode = "31", StateName = "Tripura", ShortName = "TP", CreatedBy = "SystemGenerated" },
                    new State { StateId = 32, CountryId = 1, StateCode = "32", StateName = "Uttar Pradesh", ShortName = "UP", CreatedBy = "SystemGenerated" },
                    new State { StateId = 33, CountryId = 1, StateCode = "33", StateName = "Uttarakhand", ShortName = "UK", CreatedBy = "SystemGenerated" },
                    new State { StateId = 34, CountryId = 1, StateCode = "34", StateName = "West Bengal", ShortName = "WB", CreatedBy = "SystemGenerated" }
            );

            //City
            modelBuilder.Entity<City>()
                .HasData(
                    new City { CityId = 1, StateId = 1, CityCode = "1", CityName = "Port Blair", ShortName = "PB", CreatedBy = "SystemGenerated" },
                    new City { CityId = 2, StateId = 2, CityCode = "2", CityName = "Vishakhapatnam", ShortName = "VSKP", CreatedBy = "SystemGenerated" },
                    new City { CityId = 3, StateId = 2, CityCode = "3", CityName = "Vijayawada", ShortName = "BZA", CreatedBy = "SystemGenerated" },
                    new City { CityId = 4, StateId = 2, CityCode = "4", CityName = "Guntur", ShortName = "GNT", CreatedBy = "SystemGenerated" },
                    new City { CityId = 5, StateId = 2, CityCode = "5", CityName = "Nellore", ShortName = "NLR", CreatedBy = "SystemGenerated" },
                    new City { CityId = 6, StateId = 2, CityCode = "6", CityName = "Kurnool", ShortName = "KRNT", CreatedBy = "SystemGenerated" },
                    new City { CityId = 7, StateId = 2, CityCode = "7", CityName = "Kakinada", ShortName = "CCT", CreatedBy = "SystemGenerated" },
                    new City { CityId = 8, StateId = 2, CityCode = "8", CityName = "Cuddapah", ShortName = "HX", CreatedBy = "SystemGenerated" },
                    new City { CityId = 9, StateId = 2, CityCode = "9", CityName = "Rajahmundry", ShortName = "RJY", CreatedBy = "SystemGenerated" },
                    new City { CityId = 10, StateId = 2, CityCode = "10", CityName = "Tirupati", ShortName = "TPTY", CreatedBy = "SystemGenerated" },
                    new City { CityId = 11, StateId = 2, CityCode = "11", CityName = "Anantapur", ShortName = "ATP", CreatedBy = "SystemGenerated" },
                    new City { CityId = 12, StateId = 2, CityCode = "12", CityName = "Ongole", ShortName = "OGL", CreatedBy = "SystemGenerated" },
                    new City { CityId = 13, StateId = 2, CityCode = "13", CityName = "Vizianagaram", ShortName = "VZM", CreatedBy = "SystemGenerated" },
                    new City { CityId = 14, StateId = 3, CityCode = "14", CityName = "Itanagar", ShortName = "ITN", CreatedBy = "SystemGenerated" },
                    new City { CityId = 15, StateId = 4, CityCode = "15", CityName = "Dispur", ShortName = "DSP", CreatedBy = "SystemGenerated" },
                    new City { CityId = 16, StateId = 4, CityCode = "16", CityName = "Guwahati", ShortName = "GHY", CreatedBy = "SystemGenerated" },
                    new City { CityId = 17, StateId = 5, CityCode = "17", CityName = "Patna", ShortName = "PNBE", CreatedBy = "SystemGenerated" },
                    new City { CityId = 18, StateId = 5, CityCode = "18", CityName = "Gaya", ShortName = "GAYA", CreatedBy = "SystemGenerated" },
                    new City { CityId = 19, StateId = 5, CityCode = "19", CityName = "Bhagalpur", ShortName = "BGP", CreatedBy = "SystemGenerated" },
                    new City { CityId = 20, StateId = 5, CityCode = "20", CityName = "Muzaffarpur", ShortName = "MFP", CreatedBy = "SystemGenerated" },
                    new City { CityId = 21, StateId = 5, CityCode = "21", CityName = "Purnea", ShortName = "PRNA", CreatedBy = "SystemGenerated" },
                    new City { CityId = 22, StateId = 5, CityCode = "22", CityName = "Begusarai", ShortName = "BGS", CreatedBy = "SystemGenerated" },
                    new City { CityId = 23, StateId = 6, CityCode = "23", CityName = "Chandigarh", ShortName = "CDG", CreatedBy = "SystemGenerated" },
                    new City { CityId = 24, StateId = 7, CityCode = "24", CityName = "Bhilai", ShortName = "BIA", CreatedBy = "SystemGenerated" },
                    new City { CityId = 25, StateId = 7, CityCode = "25", CityName = "Raipur", ShortName = "R", CreatedBy = "SystemGenerated" },
                    new City { CityId = 26, StateId = 7, CityCode = "26", CityName = "Bilaspur", ShortName = "BSP", CreatedBy = "SystemGenerated" },
                    new City { CityId = 27, StateId = 7, CityCode = "27", CityName = "Drug", ShortName = "DURG", CreatedBy = "SystemGenerated" },
                    new City { CityId = 28, StateId = 8, CityCode = "28", CityName = "Delhi", ShortName = "DLI", CreatedBy = "SystemGenerated" },
                    new City { CityId = 29, StateId = 8, CityCode = "29", CityName = "New Delhi", ShortName = "NDLS", CreatedBy = "SystemGenerated" },
                    new City { CityId = 30, StateId = 9, CityCode = "30", CityName = "Panaji", ShortName = "PANA", CreatedBy = "SystemGenerated" },
                    new City { CityId = 31, StateId = 10, CityCode = "31", CityName = "Ahmadabad", ShortName = "ADI", CreatedBy = "SystemGenerated" },
                    new City { CityId = 32, StateId = 10, CityCode = "32", CityName = "Surat", ShortName = "ST", CreatedBy = "SystemGenerated" },
                    new City { CityId = 33, StateId = 10, CityCode = "33", CityName = "Vadodara", ShortName = "BRC", CreatedBy = "SystemGenerated" },
                    new City { CityId = 34, StateId = 10, CityCode = "34", CityName = "Rajkot", ShortName = "RJT", CreatedBy = "SystemGenerated" },
                    new City { CityId = 35, StateId = 10, CityCode = "35", CityName = "Bhavnagar", ShortName = "BVC", CreatedBy = "SystemGenerated" },
                    new City { CityId = 36, StateId = 10, CityCode = "36", CityName = "Jamnagar", ShortName = "JAM", CreatedBy = "SystemGenerated" },
                    new City { CityId = 37, StateId = 10, CityCode = "37", CityName = "Bhuj", ShortName = "BHUJ", CreatedBy = "SystemGenerated" },
                    new City { CityId = 38, StateId = 10, CityCode = "38", CityName = "Porbandar", ShortName = "PBR", CreatedBy = "SystemGenerated" },
                    new City { CityId = 39, StateId = 10, CityCode = "39", CityName = "Ghandinagar", ShortName = "GNC", CreatedBy = "SystemGenerated" },
                    new City { CityId = 40, StateId = 10, CityCode = "40", CityName = "Daman", ShortName = "VRL", CreatedBy = "SystemGenerated" },
                    new City { CityId = 41, StateId = 11, CityCode = "41", CityName = "Faridabad", ShortName = "FDB", CreatedBy = "SystemGenerated" },
                    new City { CityId = 42, StateId = 11, CityCode = "42", CityName = "Rohtak", ShortName = "ROK", CreatedBy = "SystemGenerated" },
                    new City { CityId = 43, StateId = 11, CityCode = "43", CityName = "Hisar", ShortName = "HSR", CreatedBy = "SystemGenerated" },
                    new City { CityId = 44, StateId = 11, CityCode = "44", CityName = "Panipat", ShortName = "PNP", CreatedBy = "SystemGenerated" },
                    new City { CityId = 45, StateId = 11, CityCode = "45", CityName = "Sonipat", ShortName = "SNP", CreatedBy = "SystemGenerated" },
                    new City { CityId = 46, StateId = 11, CityCode = "46", CityName = "Karnal", ShortName = "KUN", CreatedBy = "SystemGenerated" },
                    new City { CityId = 47, StateId = 11, CityCode = "47", CityName = "Panchkula", ShortName = "PANCH", CreatedBy = "SystemGenerated" },
                    new City { CityId = 48, StateId = 12, CityCode = "48", CityName = "Shimla", ShortName = "SML", CreatedBy = "SystemGenerated" },
                    new City { CityId = 49, StateId = 13, CityCode = "49", CityName = "Srinagar", ShortName = "SINA", CreatedBy = "SystemGenerated" },
                    new City { CityId = 50, StateId = 13, CityCode = "50", CityName = "Jammu", ShortName = "JAT", CreatedBy = "SystemGenerated" },
                    new City { CityId = 51, StateId = 13, CityCode = "51", CityName = "Handwara", ShortName = "HAND", CreatedBy = "SystemGenerated" },
                    new City { CityId = 52, StateId = 14, CityCode = "52", CityName = "Jamshedpur", ShortName = "JAMS", CreatedBy = "SystemGenerated" },
                    new City { CityId = 53, StateId = 14, CityCode = "53", CityName = "Dhanbad", ShortName = "DHN", CreatedBy = "SystemGenerated" },
                    new City { CityId = 54, StateId = 14, CityCode = "54", CityName = "Ranchi", ShortName = "RNC", CreatedBy = "SystemGenerated" },
                    new City { CityId = 55, StateId = 15, CityCode = "55", CityName = "Bangalore", ShortName = "BNC", CreatedBy = "SystemGenerated" },
                    new City { CityId = 56, StateId = 15, CityCode = "56", CityName = "Mysore", ShortName = "MYS", CreatedBy = "SystemGenerated" },
                    new City { CityId = 57, StateId = 15, CityCode = "57", CityName = "Hubli", ShortName = "UBL", CreatedBy = "SystemGenerated" },
                    new City { CityId = 58, StateId = 15, CityCode = "58", CityName = "Shimoga", ShortName = "SHIM", CreatedBy = "SystemGenerated" },
                    new City { CityId = 59, StateId = 15, CityCode = "59", CityName = "Mangalore", ShortName = "MAQ", CreatedBy = "SystemGenerated" },
                    new City { CityId = 60, StateId = 15, CityCode = "60", CityName = "Davangere", ShortName = "DVG", CreatedBy = "SystemGenerated" },
                    new City { CityId = 61, StateId = 15, CityCode = "61", CityName = "Belgaum", ShortName = "BLG", CreatedBy = "SystemGenerated" },
                    new City { CityId = 62, StateId = 15, CityCode = "62", CityName = "Gulbarga", ShortName = "GR", CreatedBy = "SystemGenerated" },
                    new City { CityId = 63, StateId = 15, CityCode = "63", CityName = "Bellary", ShortName = "BAY", CreatedBy = "SystemGenerated" },
                    new City { CityId = 64, StateId = 15, CityCode = "64", CityName = "Tumkur", ShortName = "Tumkur", CreatedBy = "SystemGenerated" },
                    new City { CityId = 65, StateId = 15, CityCode = "65", CityName = "Bijapur", ShortName = "Bijapur", CreatedBy = "SystemGenerated" },
                    new City { CityId = 66, StateId = 15, CityCode = "66", CityName = "Bidar", ShortName = "Bidar", CreatedBy = "SystemGenerated" },
                    new City { CityId = 67, StateId = 15, CityCode = "67", CityName = "Hospet", ShortName = "Hospet", CreatedBy = "SystemGenerated" },
                    new City { CityId = 68, StateId = 15, CityCode = "68", CityName = "Raichur", ShortName = "Raichur", CreatedBy = "SystemGenerated" },
                    new City { CityId = 69, StateId = 16, CityCode = "69", CityName = "Thiruvananthapuram", ShortName = "Thiruvananthapuram", CreatedBy = "SystemGenerated" },
                    new City { CityId = 70, StateId = 16, CityCode = "70", CityName = "Kochi", ShortName = "Kochi", CreatedBy = "SystemGenerated" },
                    new City { CityId = 71, StateId = 16, CityCode = "71", CityName = "Calicut", ShortName = "Calicut", CreatedBy = "SystemGenerated" },
                    new City { CityId = 72, StateId = 16, CityCode = "72", CityName = "Quilon", ShortName = "Quilon", CreatedBy = "SystemGenerated" },
                    new City { CityId = 73, StateId = 16, CityCode = "73", CityName = "Trichur", ShortName = "Trichur", CreatedBy = "SystemGenerated" },
                    new City { CityId = 74, StateId = 17, CityCode = "74", CityName = "Kavaratti", ShortName = "Kavaratti", CreatedBy = "SystemGenerated" },
                    new City { CityId = 75, StateId = 18, CityCode = "75", CityName = "Indore", ShortName = "Indore", CreatedBy = "SystemGenerated" },
                    new City { CityId = 76, StateId = 18, CityCode = "76", CityName = "Bhopal", ShortName = "Bhopal", CreatedBy = "SystemGenerated" },
                    new City { CityId = 77, StateId = 18, CityCode = "77", CityName = "Jabalpur", ShortName = "Jabalpur", CreatedBy = "SystemGenerated" },
                    new City { CityId = 78, StateId = 18, CityCode = "78", CityName = "Gwalior", ShortName = "Gwalior", CreatedBy = "SystemGenerated" },
                    new City { CityId = 79, StateId = 18, CityCode = "79", CityName = "Ujjain", ShortName = "Ujjain", CreatedBy = "SystemGenerated" },
                    new City { CityId = 80, StateId = 18, CityCode = "80", CityName = "Saugor", ShortName = "Saugor", CreatedBy = "SystemGenerated" },
                    new City { CityId = 81, StateId = 18, CityCode = "81", CityName = "Sannai", ShortName = "Sannai", CreatedBy = "SystemGenerated" },
                    new City { CityId = 82, StateId = 18, CityCode = "82", CityName = "Ratlam", ShortName = "Ratlam", CreatedBy = "SystemGenerated" },
                    new City { CityId = 83, StateId = 19, CityCode = "83", CityName = "Mumbai", ShortName = "Mumbai", CreatedBy = "SystemGenerated" },
                    new City { CityId = 84, StateId = 19, CityCode = "84", CityName = "Pune", ShortName = "Pune", CreatedBy = "SystemGenerated" },
                    new City { CityId = 85, StateId = 19, CityCode = "85", CityName = "Nagpur", ShortName = "Nagpur", CreatedBy = "SystemGenerated" },
                    new City { CityId = 86, StateId = 19, CityCode = "86", CityName = "Chinchvad", ShortName = "Chinchvad", CreatedBy = "SystemGenerated" },
                    new City { CityId = 87, StateId = 19, CityCode = "87", CityName = "Kalyan", ShortName = "Kalyan", CreatedBy = "SystemGenerated" },
                    new City { CityId = 88, StateId = 19, CityCode = "88", CityName = "Nasik", ShortName = "Nasik", CreatedBy = "SystemGenerated" },
                    new City { CityId = 89, StateId = 19, CityCode = "89", CityName = "Aurangabad", ShortName = "Aurangabad", CreatedBy = "SystemGenerated" },
                    new City { CityId = 90, StateId = 19, CityCode = "90", CityName = "Thane", ShortName = "Thane", CreatedBy = "SystemGenerated" },
                    new City { CityId = 91, StateId = 19, CityCode = "91", CityName = "Bhiwandi", ShortName = "Bhiwandi", CreatedBy = "SystemGenerated" },
                    new City { CityId = 92, StateId = 19, CityCode = "92", CityName = "Solapur", ShortName = "Solapur", CreatedBy = "SystemGenerated" },
                    new City { CityId = 93, StateId = 19, CityCode = "93", CityName = "Bhayandar", ShortName = "Bhayandar", CreatedBy = "SystemGenerated" },
                    new City { CityId = 94, StateId = 19, CityCode = "94", CityName = "Kolhapur", ShortName = "Kolhapur", CreatedBy = "SystemGenerated" },
                    new City { CityId = 95, StateId = 19, CityCode = "95", CityName = "Malegaon", ShortName = "Malegaon", CreatedBy = "SystemGenerated" },
                    new City { CityId = 96, StateId = 19, CityCode = "96", CityName = "Nanded", ShortName = "Nanded", CreatedBy = "SystemGenerated" },
                    new City { CityId = 97, StateId = 19, CityCode = "97", CityName = "Chanda", ShortName = "Chanda", CreatedBy = "SystemGenerated" },
                    new City { CityId = 98, StateId = 19, CityCode = "98", CityName = "Amravati", ShortName = "Amravati", CreatedBy = "SystemGenerated" },
                    new City { CityId = 99, StateId = 19, CityCode = "99", CityName = "Ulhasnagar", ShortName = "Ulhasnagar", CreatedBy = "SystemGenerated" },
                    new City { CityId = 100, StateId = 19, CityCode = "100", CityName = "Dhulia", ShortName = "Dhulia", CreatedBy = "SystemGenerated" },
                    new City { CityId = 101, StateId = 19, CityCode = "101", CityName = "Jalgaon", ShortName = "Jalgaon", CreatedBy = "SystemGenerated" },
                    new City { CityId = 102, StateId = 19, CityCode = "102", CityName = "Sangli", ShortName = "Sangli", CreatedBy = "SystemGenerated" },
                    new City { CityId = 103, StateId = 19, CityCode = "103", CityName = "Akola", ShortName = "Akola", CreatedBy = "SystemGenerated" },
                    new City { CityId = 104, StateId = 19, CityCode = "104", CityName = "Parbhani", ShortName = "Parbhani", CreatedBy = "SystemGenerated" },
                    new City { CityId = 105, StateId = 19, CityCode = "105", CityName = "Latur", ShortName = "Latur", CreatedBy = "SystemGenerated" },
                    new City { CityId = 106, StateId = 19, CityCode = "106", CityName = "Ahmadnagar", ShortName = "Ahmadnagar", CreatedBy = "SystemGenerated" },
                    new City { CityId = 107, StateId = 19, CityCode = "107", CityName = "Ichalkaranji", ShortName = "Ichalkaranji", CreatedBy = "SystemGenerated" },
                    new City { CityId = 108, StateId = 20, CityCode = "108", CityName = "Imphal", ShortName = "Imphal", CreatedBy = "SystemGenerated" },
                    new City { CityId = 109, StateId = 21, CityCode = "109", CityName = "Shillong", ShortName = "Shillong", CreatedBy = "SystemGenerated" },
                    new City { CityId = 110, StateId = 22, CityCode = "110", CityName = "aizawl", ShortName = "aizawl", CreatedBy = "SystemGenerated" },
                    new City { CityId = 111, StateId = 23, CityCode = "111", CityName = "Kohima", ShortName = "Kohima", CreatedBy = "SystemGenerated" },
                    new City { CityId = 112, StateId = 24, CityCode = "112", CityName = "Bhubaneshwar", ShortName = "Bhubaneshwar", CreatedBy = "SystemGenerated" },
                    new City { CityId = 113, StateId = 24, CityCode = "113", CityName = "Raurkela", ShortName = "Raurkela", CreatedBy = "SystemGenerated" },
                    new City { CityId = 114, StateId = 24, CityCode = "114", CityName = "Cuttack", ShortName = "Cuttack", CreatedBy = "SystemGenerated" },
                    new City { CityId = 115, StateId = 24, CityCode = "115", CityName = "Brahmapur", ShortName = "Brahmapur", CreatedBy = "SystemGenerated" },
                    new City { CityId = 116, StateId = 24, CityCode = "116", CityName = "Sambalpur", ShortName = "Sambalpur", CreatedBy = "SystemGenerated" },
                    new City { CityId = 117, StateId = 25, CityCode = "117", CityName = "Puducherry", ShortName = "Puducherry", CreatedBy = "SystemGenerated" },
                    new City { CityId = 118, StateId = 26, CityCode = "118", CityName = "Ludhiana", ShortName = "Ludhiana", CreatedBy = "SystemGenerated" },
                    new City { CityId = 119, StateId = 26, CityCode = "119", CityName = "Amritsar", ShortName = "Amritsar", CreatedBy = "SystemGenerated" },
                    new City { CityId = 120, StateId = 26, CityCode = "120", CityName = "Jalandhar", ShortName = "Jalandhar", CreatedBy = "SystemGenerated" },
                    new City { CityId = 121, StateId = 26, CityCode = "121", CityName = "Patiala", ShortName = "Patiala", CreatedBy = "SystemGenerated" },
                    new City { CityId = 122, StateId = 27, CityCode = "122", CityName = "Jaipur", ShortName = "Jaipur", CreatedBy = "SystemGenerated" },
                    new City { CityId = 123, StateId = 27, CityCode = "123", CityName = "Kota", ShortName = "Kota", CreatedBy = "SystemGenerated" },
                    new City { CityId = 124, StateId = 27, CityCode = "124", CityName = "Jodhpur", ShortName = "Jodhpur", CreatedBy = "SystemGenerated" },
                    new City { CityId = 125, StateId = 27, CityCode = "125", CityName = "Ajmer", ShortName = "Ajmer", CreatedBy = "SystemGenerated" },
                    new City { CityId = 126, StateId = 27, CityCode = "126", CityName = "Bikaner", ShortName = "Bikaner", CreatedBy = "SystemGenerated" },
                    new City { CityId = 127, StateId = 27, CityCode = "127", CityName = "Udaipur", ShortName = "Udaipur", CreatedBy = "SystemGenerated" },
                    new City { CityId = 128, StateId = 27, CityCode = "128", CityName = "Sikar", ShortName = "Sikar", CreatedBy = "SystemGenerated" },
                    new City { CityId = 129, StateId = 27, CityCode = "129", CityName = "Bhilwara", ShortName = "Bhilwara", CreatedBy = "SystemGenerated" },
                    new City { CityId = 130, StateId = 27, CityCode = "130", CityName = "Alwar", ShortName = "Alwar", CreatedBy = "SystemGenerated" },
                    new City { CityId = 131, StateId = 27, CityCode = "131", CityName = "Bharatpur", ShortName = "Bharatpur", CreatedBy = "SystemGenerated" },
                    new City { CityId = 132, StateId = 27, CityCode = "132", CityName = "Pali", ShortName = "Pali", CreatedBy = "SystemGenerated" },
                    new City { CityId = 133, StateId = 28, CityCode = "133", CityName = "Gangtok", ShortName = "Gangtok", CreatedBy = "SystemGenerated" },
                    new City { CityId = 134, StateId = 29, CityCode = "134", CityName = "Chennai", ShortName = "Chennai", CreatedBy = "SystemGenerated" },
                    new City { CityId = 135, StateId = 29, CityCode = "135", CityName = "Madurai", ShortName = "Madurai", CreatedBy = "SystemGenerated" },
                    new City { CityId = 136, StateId = 29, CityCode = "136", CityName = "Coimbatore", ShortName = "Coimbatore", CreatedBy = "SystemGenerated" },
                    new City { CityId = 137, StateId = 29, CityCode = "137", CityName = "Trichinopoly", ShortName = "Trichinopoly", CreatedBy = "SystemGenerated" },
                    new City { CityId = 138, StateId = 29, CityCode = "138", CityName = "Salem", ShortName = "Salem", CreatedBy = "SystemGenerated" },
                    new City { CityId = 139, StateId = 29, CityCode = "139", CityName = "Tiruppur", ShortName = "Tiruppur", CreatedBy = "SystemGenerated" },
                    new City { CityId = 140, StateId = 29, CityCode = "140", CityName = "Tinnevelly", ShortName = "Tinnevelly", CreatedBy = "SystemGenerated" },
                    new City { CityId = 141, StateId = 29, CityCode = "141", CityName = "Tuticorin", ShortName = "Tuticorin", CreatedBy = "SystemGenerated" },
                    new City { CityId = 142, StateId = 29, CityCode = "142", CityName = "Rajapalaiyam", ShortName = "Rajapalaiyam", CreatedBy = "SystemGenerated" },
                    new City { CityId = 143, StateId = 29, CityCode = "143", CityName = "Nagercoil", ShortName = "Nagercoil", CreatedBy = "SystemGenerated" },
                    new City { CityId = 144, StateId = 29, CityCode = "144", CityName = "Tanjore", ShortName = "Tanjore", CreatedBy = "SystemGenerated" },
                    new City { CityId = 145, StateId = 30, CityCode = "145", CityName = "Hyderabad", ShortName = "Hyderabad", CreatedBy = "SystemGenerated" },
                    new City { CityId = 146, StateId = 30, CityCode = "146", CityName = "Warangal", ShortName = "Warangal", CreatedBy = "SystemGenerated" },
                    new City { CityId = 147, StateId = 30, CityCode = "147", CityName = "Nizamabad", ShortName = "Nizamabad", CreatedBy = "SystemGenerated" },
                    new City { CityId = 148, StateId = 30, CityCode = "148", CityName = "Karimnagar", ShortName = "Karimnagar", CreatedBy = "SystemGenerated" },
                    new City { CityId = 149, StateId = 30, CityCode = "149", CityName = "Ramgundam", ShortName = "Ramgundam", CreatedBy = "SystemGenerated" },
                    new City { CityId = 150, StateId = 30, CityCode = "150", CityName = "Kagaznagar", ShortName = "Kagaznagar", CreatedBy = "SystemGenerated" },
                    new City { CityId = 151, StateId = 31, CityCode = "151", CityName = "Agartala", ShortName = "Agartala", CreatedBy = "SystemGenerated" },
                    new City { CityId = 152, StateId = 32, CityCode = "152", CityName = "Lucknow", ShortName = "Lucknow", CreatedBy = "SystemGenerated" },
                    new City { CityId = 153, StateId = 32, CityCode = "153", CityName = "Cawnpore", ShortName = "Cawnpore", CreatedBy = "SystemGenerated" },
                    new City { CityId = 154, StateId = 32, CityCode = "154", CityName = "Mirzapur", ShortName = "Mirzapur", CreatedBy = "SystemGenerated" },
                    new City { CityId = 155, StateId = 32, CityCode = "155", CityName = "Ghaziabad", ShortName = "Ghaziabad", CreatedBy = "SystemGenerated" },
                    new City { CityId = 156, StateId = 32, CityCode = "156", CityName = "agra", ShortName = "agra", CreatedBy = "SystemGenerated" },
                    new City { CityId = 157, StateId = 32, CityCode = "157", CityName = "Meerut", ShortName = "Meerut", CreatedBy = "SystemGenerated" },
                    new City { CityId = 158, StateId = 32, CityCode = "158", CityName = "Allahabad", ShortName = "Allahabad", CreatedBy = "SystemGenerated" },
                    new City { CityId = 159, StateId = 32, CityCode = "159", CityName = "Varanasi", ShortName = "Varanasi", CreatedBy = "SystemGenerated" },
                    new City { CityId = 160, StateId = 32, CityCode = "160", CityName = "Aligarh", ShortName = "Aligarh", CreatedBy = "SystemGenerated" },
                    new City { CityId = 161, StateId = 32, CityCode = "161", CityName = "Bareilly", ShortName = "Bareilly", CreatedBy = "SystemGenerated" },
                    new City { CityId = 162, StateId = 32, CityCode = "162", CityName = "Moradabad", ShortName = "Moradabad", CreatedBy = "SystemGenerated" },
                    new City { CityId = 163, StateId = 32, CityCode = "163", CityName = "Saharanpur", ShortName = "Saharanpur", CreatedBy = "SystemGenerated" },
                    new City { CityId = 164, StateId = 32, CityCode = "164", CityName = "Gorakhpur", ShortName = "Gorakhpur", CreatedBy = "SystemGenerated" },
                    new City { CityId = 165, StateId = 32, CityCode = "165", CityName = "Jhansi", ShortName = "Jhansi", CreatedBy = "SystemGenerated" },
                    new City { CityId = 166, StateId = 32, CityCode = "166", CityName = "Muzaffarnagar", ShortName = "Muzaffarnagar", CreatedBy = "SystemGenerated" },
                    new City { CityId = 167, StateId = 32, CityCode = "167", CityName = "Mathura", ShortName = "Mathura", CreatedBy = "SystemGenerated" },
                    new City { CityId = 168, StateId = 32, CityCode = "168", CityName = "Shahjanpur", ShortName = "Shahjanpur", CreatedBy = "SystemGenerated" },
                    new City { CityId = 169, StateId = 32, CityCode = "169", CityName = "Firozabad", ShortName = "Firozabad", CreatedBy = "SystemGenerated" },
                    new City { CityId = 170, StateId = 32, CityCode = "170", CityName = "Rampur", ShortName = "Rampur", CreatedBy = "SystemGenerated" },
                    new City { CityId = 171, StateId = 32, CityCode = "171", CityName = "Etawah", ShortName = "Etawah", CreatedBy = "SystemGenerated" },
                    new City { CityId = 172, StateId = 32, CityCode = "172", CityName = "Hapur", ShortName = "Hapur", CreatedBy = "SystemGenerated" },
                    new City { CityId = 173, StateId = 32, CityCode = "173", CityName = "Sambhal", ShortName = "Sambhal", CreatedBy = "SystemGenerated" },
                    new City { CityId = 174, StateId = 33, CityCode = "174", CityName = "Dehra Dun", ShortName = "Dehra Dun", CreatedBy = "SystemGenerated" },
                    new City { CityId = 175, StateId = 34, CityCode = "175", CityName = "Kolkata", ShortName = "Kolkata", CreatedBy = "SystemGenerated" },
                    new City { CityId = 176, StateId = 34, CityCode = "176", CityName = "Haora", ShortName = "Haora", CreatedBy = "SystemGenerated" },
                    new City { CityId = 177, StateId = 34, CityCode = "177", CityName = "Durgapur", ShortName = "Durgapur", CreatedBy = "SystemGenerated" },
                    new City { CityId = 178, StateId = 34, CityCode = "178", CityName = "asansol", ShortName = "asansol", CreatedBy = "SystemGenerated" },
                    new City { CityId = 179, StateId = 34, CityCode = "179", CityName = "Bhatpara", ShortName = "Bhatpara", CreatedBy = "SystemGenerated" },
                    new City { CityId = 180, StateId = 34, CityCode = "180", CityName = "Panihati", ShortName = "Panihati", CreatedBy = "SystemGenerated" },
                    new City { CityId = 181, StateId = 34, CityCode = "181", CityName = "Kamarhati", ShortName = "Kamarhati", CreatedBy = "SystemGenerated" },
                    new City { CityId = 182, StateId = 34, CityCode = "182", CityName = "Barddhaman", ShortName = "Barddhaman", CreatedBy = "SystemGenerated" },
                    new City { CityId = 183, StateId = 34, CityCode = "183", CityName = "Kulti", ShortName = "Kulti", CreatedBy = "SystemGenerated" },
                    new City { CityId = 184, StateId = 34, CityCode = "184", CityName = "Shiliguri", ShortName = "Shiliguri", CreatedBy = "SystemGenerated" },
                    new City { CityId = 185, StateId = 34, CityCode = "185", CityName = "Bali", ShortName = "Bali", CreatedBy = "SystemGenerated" },
                    new City { CityId = 186, StateId = 34, CityCode = "186", CityName = "Barasat", ShortName = "Barasat", CreatedBy = "SystemGenerated" },
                    new City { CityId = 187, StateId = 34, CityCode = "187", CityName = "Uluberiya", ShortName = "Uluberiya", CreatedBy = "SystemGenerated" }
                );
        }
    }
}
